config/routes.rb
Zigotto::Application.routes.draw do
  resources :protocols

  resources :layers
	root :to => 'home#index'
end

app/models/layer.rb
class Layer < ActiveRecord::Base
	has_many :protocols
  attr_accessible :description, :nome
  validates :nome, :presence => true
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
  belongs_to :layer
  attr_accessible :description, :name, :layer_id
  validates :name, :layer, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController

  def index
    @layers = Layer.all

    respond_to do |format|
      format.html 
      format.json { render json: @layers }
    end
  end

 
  def show
    @layer = Layer.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @layer }
    end
  end

 
  def new
    @layer = Layer.new

    respond_to do |format|
      format.html 
      format.json { render json: @layer }
    end
  end

  def edit
    @layer = Layer.find(params[:id])
  end

  def create
    @layer = Layer.new(params[:layer])

    respond_to do |format|
      if @layer.save
        format.html { redirect_to @layer, notice: 'Camada criada com sucesso.' }
        format.json { render json: @layer, status: :created, location: @layer }
      else
        format.html { render action: "new" }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @layer = Layer.find(params[:id])

    respond_to do |format|
      if @layer.update_attributes(params[:layer])
        format.html { redirect_to @layer, notice: 'Camada atualizada com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @layer = Layer.find(params[:id])
    @layer.destroy

    respond_to do |format|
      format.html { redirect_to layers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  
  def index
    @protocols = Protocol.all

    respond_to do |format|
      format.html 
      format.json { render json: @protocols }
    end
  end

  def show
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @protocol }
    end
  end

  def new
    @protocol = Protocol.new

    respond_to do |format|
      format.html 
      format.json { render json: @protocol }
    end
  end

  def edit
    @protocol = Protocol.find(params[:id])
  end

  def create
    @protocol = Protocol.new(params[:protocol])

    respond_to do |format|
      if @protocol.save
        format.html { redirect_to @protocol, notice: 'Protocolo criado com sucesso.' }
        format.json { render json: @protocol, status: :created, location: @protocol }
      else
        format.html { render action: "new" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      if @protocol.update_attributes(params[:protocol])
        format.html { redirect_to @protocol, notice: 'Protocolo atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @protocol = Protocol.find(params[:id])
    @protocol.destroy

    respond_to do |format|
      format.html { redirect_to protocols_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/views/home/index.html.haml
%h1 Zigotto

app/views/layers/_form.html.haml
= simple_form_for @layer, :html => { :class => 'form-horizontal' } do |f|
  = f.input :nome
  = f.input :description, :input_html => { rows: 4}
  .form-actions
    = f.button :submit, "Cadastrar", :class => 'btn btn-primary'
    = link_to "Cancelar", layers_path, :class => 'btn'

app/views/layers/edit.html.haml
.page-header
  %h1 Editar Camada
= render :partial => "form"

app/views/layers/index.html.haml
.page-header
  %h1 Camadas
%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Nome
      %th Descrição
      %th Criado em
      %th Ações
  %tbody
    - @layers.each do |layer|
      %tr
        %td= link_to layer.id, layer_path(layer)
        %td= layer.nome
        %td= layer.description
        %td=l layer.created_at
        %td
          = link_to "Editar", edit_layer_path(layer), :class => 'btn btn-mini'
          = link_to "deletar", layer_path(layer), :method => :delete, :data => { :confirm => "Tem Certeza?" }, :class => 'btn btn-mini btn-danger'

= link_to "Nova Camada", new_layer_path, :class => 'btn btn-primary'

app/views/layers/new.html.haml
.page-header
  %h1 Nova Camada
= render :partial => "form"

app/views/layers/show.html.haml
.page-header
  %h1= @layer.nome

= simple_format @layer.description

.form-actions
  = link_to "Voltar", layers_path, :class => 'btn'
  = link_to "Editar", edit_layer_path(@layer), :class => 'btn'
  = link_to "Deletar", layer_path(@layer), :method => "delete", :data => { :confirm => "Tem certeza?" }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Zigotto"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Zigotto
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/protocols/_form.html.haml
= simple_form_for @protocol, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :description, :input_html => { rows: 4 }
  = f.association :layer, :as => :select, :collection => Layer.all.map{|l| [l.nome, l.id]}
  .form-actions
    = f.button :submit, "Cadastrar", :class => 'btn btn-primary'
    = link_to "Cancelar", protocols_path, :class => 'btn'

app/views/protocols/edit.html.haml
.page-header
  %h1 Editar Protocolo
= render :partial => "form"

app/views/protocols/index.html.haml
.page-header
  %h1 Protocolos
%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Nome
      %th Descrição
      %th Layer
      %th Criado em 
      %th Ações
  %tbody
    - @protocols.each do |protocol|
      %tr
        %td= link_to protocol.id, protocol_path(protocol)
        %td= protocol.name
        %td= protocol.description
        %td= protocol.layer_id
        %td=l protocol.created_at
        %td
          = link_to "Editar", edit_protocol_path(protocol), :class => 'btn btn-mini'
          = link_to "Excluir", protocol_path(protocol), :method => :delete, :data => { :confirm => "Tem Certeza?" }, :class => 'btn btn-mini btn-danger'

= link_to "Novo Protocolo	", new_protocol_path, :class => 'btn btn-primary'

app/views/protocols/new.html.haml
.page-header
  %h1= @protocol.name
= render :partial => "form"

app/views/protocols/show.html.haml
- model_class = Protocol
.page-header
  %h1= @protocol.name

= simple_format @protocol.description
%p
  %strong Camada
  %br
  = @protocol.layer.nome

.form-actions
  = link_to "Voltar", protocols_path, :class => 'btn'
  = link_to "Editar", edit_protocol_path(@protocol), :class => 'btn'
  = link_to "Excluir", protocol_path(@protocol), :method => "delete", :data => { :confirm => "Tem Certeza?" }, :class => 'btn btn-danger'